workflow "update boards with issues" {
  on = "issues"
  resolves = ["Create Azure Boards Work Item"]
}

action "Create Azure Boards Work Item" {
  uses = "azure/github-actions/boards@master"
  env = {
    AZURE_DEVOPS_URL = "https://dev.azure.com/marciotedesco" #ADO URL
    AZURE_DEVOPS_PROJECT = "GitHub-demo" #ADO Project
    AZURE_BOARDS_TYPE = "Task" #Board Type...this is from the ADO
  }
  secrets = ["AZURE_DEVOPS_TOKEN"] #ADO Token from your security settings
}
